---
title: "Estrategias para la Seguridad Economica en la Vejez"
date: "20-08-2020"
output: html_document
---


<br>

La presente investigación busca dar cuenta de las diferencias entre las tendencias de las estrategias empleadas por individuos en edad de jubilación-bajo el sistema de capitalización individual(Administradora de Fondos de Pensiones)- para alcanzar la seguridad económica -o, según el caso, las condiciones mínimas de supervivencia- acorde a su posición de género y de clase, en las comunas de Lo Barnechea y San Bernardo.Con este fin, la pregunta de investigación es la siguiente: ¿Cuáles son las diferencias en las tendencias de uso de estrategias económicas durante la vejez según género y clase social en Santiago, 2018?

<br>
Autoras:
<br>

Josefina Carrasco: josefina.carrasco@ug.uchile.cl
<br>
Isidora Didier: isidora.didier@ug.uchile.cl
<br>
Valentina González: vale5544@gmail.com
<br>
Karen Tapia: karentsepulveda@gmail.com
<br>
Martina Silva: martina.silva@ug.uchile.cl
<br>

